name: Unit test Cuentas

on: [push]

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./src

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: build test
        run: javac -sourcepath ./src -cp "./lib/*" ./src/common/Main.java # Path to the main file and source folder
        working-directory: ${{env.working-directory}}
