name: Unit test Prestamos

on: [push]

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./src

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: build test
        run: javac -sourcepath ./src -cp "./lib/*" ./src/test/TestSubPrestamos.java # Path to the main file and source folder
        working-directory: ${{env.working-directory}}

      - name: execute test Usuarios
        if: ${{ success() }} # Only starts if the previous steps worked
        run: java -cp "../lib/*;./*;." org.junit.runner.JUnitCore test.TestSubPrestamos # Path to the .class of main, arguments for the game and the input file
        working-directory: ./src/src
